# 10-5-18: upgrading to Rails 5.2; this entire file appears to be removed
# secrets (encoded) will live in credentials.yml.enc ?
# not removing just yet, until I understand this correctly, to not break stuff

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339708b70b2d2998ea277e5d0fe370fc791b4ed9a1c40128037316a7bb460f085ccd18f30aa0a5ff625f047d9b212f60a9e6a5d7746f737fc5c24982df853c99

test:
  secret_key_base: 600214dfdcd25f75c746bfb0aa524e631f9b58b9dff303c20c01c3f941b32e74a695c029db5c0ef675e3dcb2666d7185c4316eb736985910030faa0951fca022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

################################################################################
# 5-3-17, Original, before R5 upgrade:
# development:
#   secret_key_base: a8c781a4c8e1ed9872eca5a4d56d69443af03e554de9347e171cd22d536a9ba35e1a6505790ebb1312d5b2e187f2f79d12cb4a1b993ad5797ba5cbf9f7333ecb
#
# test:
#   secret_key_base: c0ac7c163e896b19744de918cbb74713b18c3fe026a3bd6f893eeafddc2dae963b4f1edfaddf2ced93e352b115d9915f9df9f250fedc8344757008e1760d65db
#
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
